packages:
  - 'src/leafer'
  - 'src/leafer/packages/*'
  - 'src/leafer/packages/platform/*'
  - 'src/leafer/packages/display-module/*'
  - 'src/leafer/packages/canvas/*'
  - 'src/leafer/packages/image/*'
  - 'src/leafer/packages/partner/*'
  - 'src/ui'
  - 'src/ui/packages/*'
  - 'src/ui/packages/core/*'
  - 'src/ui/packages/platform/*'
  - 'src/ui/packages/display-module/*'
  - 'src/ui/packages/interaction/*'
  - 'src/ui/packages/partner/*'
  - 'src/draw'
  - 'src/draw/packages/*'
  - 'src/draw/packages/platform/*'
  - 'src/in'
  - 'src/in/packages/*'
